# Data Wrangling online job postings

### Gather

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('online-job-postings.csv')
df.head()

,jobpost,date,Title,Company,AnnouncementCode,Term,Eligibility,Audience,StartDate,Duration,...,Salary,ApplicationP,OpeningDate,Deadline,Notes,AboutC,Attach,Year,Month,IT
0,AMERIA Investment Consulting Company\r\nJOB TI...,"Jan 5, 2004",Chief Financial Officer,AMERIA Investment Consulting Company,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"To apply for this position, please submit a\r\...",NaN,26 January 2004,NaN,NaN,NaN,2004,1,False
1,International Research & Exchanges Board (IREX...,"Jan 7, 2004",Full-time Community Connections Intern (paid i...,International Research & Exchanges Board (IREX),NaN,NaN,NaN,NaN,NaN,3 months,...,NaN,Please submit a cover letter and resume to:\r\...,NaN,12 January 2004,NaN,The International Research & Exchanges Board (...,NaN,2004,1,False
2,Caucasus Environmental NGO Network (CENN)\r\nJ...,"Jan 7, 2004",Country Coordinator,Caucasus Environmental NGO Network (CENN),NaN,NaN,NaN,NaN,NaN,Renewable annual contract\r\nPOSITION,...,NaN,Please send resume or CV toursula.kazarian@......,NaN,20 January 2004\r\nSTART DATE: February 2004,NaN,The Caucasus Environmental NGO Network is a\r\...,NaN,2004,1,False
3,Manoff Group\r\nJOB TITLE: BCC Specialist\r\n...,"Jan 7, 2004",BCC Specialist,Manoff Group,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Please send cover letter and resume to Amy\r\n...,NaN,23 January 2004\r\nSTART DATE: Immediate,NaN,NaN,NaN,2004,1,False
4,Yerevan Brandy Company\r\nJOB TITLE: Software...,"Jan 10, 2004",Software Developer,Yerevan Brandy Company,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Successful candidates should submit\r\n- CV; \...,NaN,"20 January 2004, 18:00",NaN,NaN,NaN,2004,1,True

### Assess

1. NaN values
2. Start date inconsistencies(same way of saying immediately, asap etc...)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19001 entries, 0 to 19000
Data columns (total 24 columns):
jobpost             19001 non-null object
date                19001 non-null object
Title               18973 non-null object
Company             18994 non-null object
AnnouncementCode    1208 non-null object
Term                7676 non-null object
Eligibility         4930 non-null object
Audience            640 non-null object
StartDate           9675 non-null object
Duration            10798 non-null object
Location            18969 non-null object
JobDescription      15109 non-null object
JobRequirment       16479 non-null object
RequiredQual        18517 non-null object
Salary              9622 non-null object
ApplicationP        18941 non-null object
OpeningDate         18295 non-null object
Deadline            18936 non-null object
Notes               2211 non-null object
AboutC              12470 non-null object
Attach              1559 non-null object
Year                19001 non-null int64
Month               19001 non-null int64
IT                  19001 non-null bool
dtypes: bool(1), int64(2), object(21)
memory usage: 3.4+ MB

Fix non descriptive columns(AboutC,ApplicationP...)

In [5]:
df['Company'].value_counts()

ArmenTel CJSC                                                                             353
World Vision Armenia                                                                      239
Mentor Graphics Development Services CJSC                                                 236
Career Center NGO                                                                         229
Orange Armenia                                                                            203
Ameriabank CJSC                                                                           196
Converse Bank CJSC                                                                        161
SAS Group LLC                                                                             150
UNDP Armenia Office                                                                       132
Energize Global Services CJSC                                                             126
Central Bank of Armenia                                                                   126
OSCE Office in Yerevan                                                                    125
HSBC Bank Armenia CJSC                                                                    117
VTB Bank (Armenia) CJSC                                                                   113
Inecobank CJSC                                                                            113
Synopsys Armenia                                                                          112
Ardshininvestbank CJSC                                                                    108
"Coca-Cola Hellenic Bottling Company Armenia" CJSC                                        105
Lycos Europe                                                                              103
Boomerang Software LLC                                                                     84
Synopsys Armenia CJSC                                                                      81
Haypost CJSC                                                                               78
Orange Armenia CJSC                                                                        78
ProCredit Bank                                                                             77
Prometey Bank LLC                                                                          76
"Aregak" Universal Credit Organization CJSC                                                75
CQGI MA                                                                                    72
AtTask                                                                                     70
Questrade Armenia                                                                          69
Zeppelin Armenia LLC                                                                       64
                                                                                         ...
LAM LLC                                                                                     1
MCA- Armenia                                                                                1
A.I. Alikhanian National Scientific Laboratory (YerPhI) Foundation                          1
"Tanger" recruitment company for a Plant                                                    1
Marketing Professional Group LLC                                                            1
Small and Medium Business Union (SMBU)                                                      1
Kalpataru Power Transmission Limited Branch in the Republic of Armenia                      1
GTZ- Regional Tuberculosis Control Programme, Southern Caucasus, Yerevan\r\nOffice          1
US DEPARTMENT OF AGRICULTURE \r\nMARKETING ASSISTANCE PROJECT                               1
Caucasian Refugees and IDPs NGO Network (CRINGO)                                            1
Solvay Pharma                                                                               1
Actitour LLC                                                                                1
Small and Medium Entrepreneurship Development National Center (SME DNC)\r\nof Armenia       1
Enerpac Exclusive Representation in Armenia                                                 1
Kamurj UCO LLC                                                                              1
Save the Children International in Armenia                                                  1
Center for Organizing Youth Activities                                                      1
Central Station                                                                             1
"Intermed" LLC                                                                              1
Rural Finance Facility - PIU SI                                                             1
"Karamyan & Mkhitaryan Friends" LLC /KM Construction/                                       1
"Atlas Copco Central Asia"                                                                  1
"Tire" LLC                                                                                  1
Media Initiatives Center NGO                                                                1
Smart Units Ltd.                                                                            1
Link Ltd.                                                                                   1
JET Investments CJSC                                                                        1
Margasoft Corp, Armenian Branch Office                                                      1
MP - Hi Tech                                                                                1
Cascade Insurance and Reinsurance Company (CIRCO) and Cascade Capital\r\nHoldings(CCH)      1
Name: Company, Length: 4554, dtype: int64

In [6]:
df.tail(5)

,jobpost,date,Title,Company,AnnouncementCode,Term,Eligibility,Audience,StartDate,Duration,...,Salary,ApplicationP,OpeningDate,Deadline,Notes,AboutC,Attach,Year,Month,IT
18996,Technolinguistics NGO\r\n\r\n\r\nTITLE: Senio...,"Dec 28, 2015",Senior Creative UX/ UI Designer,Technolinguistics NGO,NaN,Full-time,NaN,NaN,NaN,Long-term,...,Competitive,"To apply for this position, please send your\r...",29 December 2015,28 January 2016,NaN,As a company Technolinguistics has a mandate t...,NaN,2015,12,False
18997,"""Coca-Cola Hellenic Bottling Company Armenia"" ...","Dec 30, 2015",Category Development Manager,"""Coca-Cola Hellenic Bottling Company Armenia"" ...",NaN,Full-time,All interested professionals.,NaN,ASAP,Long-term with a probation period of 3 months.,...,NaN,All interested candidates are kindly requested...,30 December 2015,20 January 2016,NaN,NaN,NaN,2015,12,False
18998,"""Coca-Cola Hellenic Bottling Company Armenia"" ...","Dec 30, 2015",Operational Marketing Manager,"""Coca-Cola Hellenic Bottling Company Armenia"" ...",NaN,Full-time,All interested professionals.,NaN,ASAP,Long-term with a probation period of 3 months.,...,NaN,All interested candidates are kindly requested...,30 December 2015,20 January 2016,NaN,NaN,NaN,2015,12,False
18999,San Lazzaro LLC\r\n\r\n\r\nTITLE: Head of O...,"Dec 30, 2015",Head of Online Sales Department,San Lazzaro LLC,NaN,NaN,NaN,NaN,NaN,Long-term,...,Highly competitive,Interested candidates can send their CVs to:\r...,30 December 2015,29 January 2016,NaN,San Lazzaro LLC works with several internation...,NaN,2015,12,False
19000,"""Kamurj"" UCO CJSC\r\n\r\n\r\nTITLE: Lawyer in...","Dec 30, 2015",Lawyer in Legal Department,"""Kamurj"" UCO CJSC",NaN,Full-time,NaN,NaN,NaN,Indefinite,...,NaN,All qualified applicants are encouraged to\r\n...,30 December 2015,20 January 2016,NaN,"""Kamurj"" UCO CJSC is providing micro and small...",NaN,2015,12,False

### Clean

Define:
   1. StartDate inconsistencies (ASAP)
   2. Nondescriptive column headers (ApplicationP, AboutC, RequiredQual ... and also JobRequirment)

Code

In [7]:
df_clean = df.copy()

Select all nondescriptive and misspelled column headers (ApplicationP, AboutC, RequiredQual, JobRequirment) and replace them with full words (ApplicationProcedure, AboutCompany, RequiredQualifications, JobRequirement)

In [15]:
df_clean = df_clean.rename(columns = {'ApplicationP': 'ApplicationProcedure','AboutC': 'AboutCompany','RequiredQual': 'RequiredQualifications','JobRequirment':'JobRequirements'})

Select all records in the StartDate column that have "As soon as possible", "Immediately", etc. and replace the text in those cells with "ASAP"

In [17]:
asap_list = ['Immediately', 'As soon as possible', 'Upon hiring',
             'Immediate', 'Immediate employment', 'As soon as possible.', 'Immediate job opportunity',
             '"Immediate employment, after passing the interview."',
             'ASAP preferred', 'Employment contract signature date',
             'Immediate employment opportunity', 'Immidiately', 'ASA',
             'Asap', '"The position is open immediately but has a flexible start date depending on the candidates earliest availability."',
             'Immediately upon agreement', '20 November 2014 or ASAP',
             'immediately', 'Immediatelly',
             '"Immediately upon selection or no later than November 15, 2009."',
             'Immediate job opening', 'Immediate hiring', 'Upon selection',
             'As soon as practical', 'Immadiate', 'As soon as posible',
             'Immediately with 2 months probation period',
             '12 November 2012 or ASAP', 'Immediate employment after passing the interview',
             'Immediately/ upon agreement', '01 September 2014 or ASAP',
             'Immediately or as per agreement', 'as soon as possible',
             'As soon as Possible', 'in the nearest future', 'immediate',
             '01 April 2014 or ASAP', 'Immidiatly', 'Urgent',
             'Immediate or earliest possible', 'Immediate hire',
             'Earliest  possible', 'ASAP with 3 months probation period.',
             'Immediate employment opportunity.', 'Immediate employment.',
             'Immidietly', 'Imminent', 'September 2014 or ASAP', 'Imediately']

In [22]:
for phrase in asap_list:
    df_clean.StartDate.replace(phrase,'ASAP',inplace = True)

Test

In [24]:
# test for renamed columns
df_clean.columns

Index(['jobpost', 'date', 'Title', 'Company', 'AnnouncementCode', 'Term',
       'Eligibility', 'Audience', 'StartDate', 'Duration', 'Location',
       'JobDescription', 'JobRequirement', 'RequiredQualifications', 'Salary',
       'ApplicationProcedure', 'OpeningDate', 'Deadline', 'Notes',
       'AboutCompany', 'Attach', 'Year', 'Month', 'IT'],
      dtype='object')

In [25]:
# check if ASAP is visible
df_clean['StartDate'].value_counts()

ASAP                                                             6856
01 September 2012                                                  31
March 2006                                                         27
November 2006                                                      22
January 2010                                                       19
01 February 2005                                                   17
February 2014                                                      17
TBD                                                                16
February 2011                                                      16
September 2010                                                     16
September 2008                                                     15
March 2011                                                         15
01 July 2014                                                       14
February 2007                                                      14
01 February 2015                                                   14
01 September 2008                                                  13
01 March 2006                                                      13
January 2016                                                       13
01 September 2010                                                  13
01 April 2014                                                      12
01 March 2012                                                      12
June 2008                                                          12
01 October 2008                                                    12
September 2013                                                     12
01 October 2012                                                    12
Fall 2010                                                          12
01 November 2007                                                   11
01 April 2012                                                      11
January 2011                                                       11
01 September 2013                                                  11
                                                                 ...
01 November 2010                                                    1
01 June 2007, the latest 01 July 2007                               1
25 July 2005                                                        1
14 May 2005, at 14.00                                               1
Mid. August                                                         1
24 January 2011                                                     1
24 January 2005                                                     1
11 November 2013                                                    1
21 June 2007                                                        1
Anticipated starting date of the assignment is March\r\n2008.       1
15 October 2014                                                     1
10 January 2014                                                     1
25 March 2009                                                       1
05 March 2012                                                       1
03 February 2014                                                    1
20 December 2005                                                    1
26 April 2014                                                       1
10 October 2013 (negotiable)                                        1
18 April 2007                                                       1
12 January 2005                                                     1
02\r\nNovember 201                                                  1
17 February 2014                                                    1
June 1, 2007                                                        1
Between 2004-06-28 12:00 AM and 2004-07-02 12:00 AM                 1
08 June 2011                                                        1
6 November 2004                                                     1
19 September 2007                                                   1
10 February 2005                                                    1
19 December 2007                                                    1
25 July 2012                                                        1
Name: StartDate, Length: 1140, dtype: int64

In [32]:
assert 2 + 2 == 5

AssertionError:

In [31]:
assert 2 + 3 == 5

In [30]:
for phrase in asap_list:
    assert phrase not in df_clean.StartDate.values